# Form implementation generated from reading ui file 'delete_vendor_confirm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogDeleteVendor(object):
    def setupUi(self, DialogDeleteVendor):
        DialogDeleteVendor.setObjectName("DialogDeleteVendor")
        DialogDeleteVendor.resize(423, 137)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DialogDeleteVendor)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelQuestion = QtWidgets.QLabel(parent=DialogDeleteVendor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelQuestion.sizePolicy().hasHeightForWidth())
        self.labelQuestion.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.labelQuestion.setFont(font)
        self.labelQuestion.setScaledContents(False)
        self.labelQuestion.setWordWrap(True)
        self.labelQuestion.setObjectName("labelQuestion")
        self.verticalLayout.addWidget(self.labelQuestion)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogDeleteVendor)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(DialogDeleteVendor)
        self.buttonBox.accepted.connect(DialogDeleteVendor.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogDeleteVendor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogDeleteVendor)

    def retranslateUi(self, DialogDeleteVendor):
        _translate = QtCore.QCoreApplication.translate
        DialogDeleteVendor.setWindowTitle(_translate("DialogDeleteVendor", "Confirmació"))
        self.labelQuestion.setText(_translate("DialogDeleteVendor", "<html><head/><body><p>De debó desitja eliminar el proveïdor <span style=\" font-weight:700;\">vendorName (vendorNIF)</span>?</p></body></html>"))
