# Form implementation generated from reading ui file 'src\ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 511)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 22))
        self.menubar.setObjectName("menubar")
        self.menuVendors = QtWidgets.QMenu(parent=self.menubar)
        self.menuVendors.setObjectName("menuVendors")
        self.menuInvoices = QtWidgets.QMenu(parent=self.menubar)
        self.menuInvoices.setObjectName("menuInvoices")
        self.menuReports = QtWidgets.QMenu(parent=self.menubar)
        self.menuReports.setObjectName("menuReports")
        MainWindow.setMenuBar(self.menubar)
        self.actionProva = QtGui.QAction(parent=MainWindow)
        self.actionProva.setObjectName("actionProva")
        self.mainVendorsAction = QtGui.QAction(parent=MainWindow)
        self.mainVendorsAction.setObjectName("mainVendorsAction")
        self.mainInvoicesAction = QtGui.QAction(parent=MainWindow)
        self.mainInvoicesAction.setObjectName("mainInvoicesAction")
        self.mainreportsAction = QtGui.QAction(parent=MainWindow)
        self.mainreportsAction.setObjectName("mainreportsAction")
        self.menuVendors.addAction(self.mainVendorsAction)
        self.menuInvoices.addAction(self.mainInvoicesAction)
        self.menuReports.addAction(self.mainreportsAction)
        self.menubar.addAction(self.menuVendors.menuAction())
        self.menubar.addAction(self.menuInvoices.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestion S"))
        self.menuVendors.setTitle(_translate("MainWindow", "Proveïdors"))
        self.menuInvoices.setTitle(_translate("MainWindow", "Factures"))
        self.menuReports.setTitle(_translate("MainWindow", "Informes"))
        self.actionProva.setText(_translate("MainWindow", "Prova"))
        self.mainVendorsAction.setText(_translate("MainWindow", "Mostra"))
        self.mainInvoicesAction.setText(_translate("MainWindow", "Mostra"))
        self.mainreportsAction.setText(_translate("MainWindow", "Mostra"))
