# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 516)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("""background-image: url(\'ruta/a/imagen.jpg\');
                                         background-position: center;
                                         background-repeat: no-repeat;""")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 22))
        self.menubar.setObjectName("menubar")
        self.menuProve_dors = QtWidgets.QMenu(parent=self.menubar)
        self.menuProve_dors.setObjectName("menuProve_dors")
        self.menuFacrures = QtWidgets.QMenu(parent=self.menubar)
        self.menuFacrures.setObjectName("menuFacrures")
        self.menuInformes = QtWidgets.QMenu(parent=self.menubar)
        self.menuInformes.setObjectName("menuInformes")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuProve_dors.menuAction())
        self.menubar.addAction(self.menuFacrures.menuAction())
        self.menubar.addAction(self.menuInformes.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gestion S"))
        self.menuProve_dors.setTitle(_translate("MainWindow", "Proveïdors"))
        self.menuFacrures.setTitle(_translate("MainWindow", "Factures"))
        self.menuInformes.setTitle(_translate("MainWindow", "Informes"))
