# Form implementation generated from reading ui file 'reports.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ShowReports(object):
    def setupUi(self, ShowReports):
        ShowReports.setObjectName("ShowReports")
        ShowReports.resize(743, 485)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ShowReports)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelEndDate = QtWidgets.QLabel(parent=ShowReports)
        self.labelEndDate.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.labelEndDate.setObjectName("labelEndDate")
        self.horizontalLayout_2.addWidget(self.labelEndDate)
        self.labelStartDate = QtWidgets.QLabel(parent=ShowReports)
        self.labelStartDate.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelStartDate.setObjectName("labelStartDate")
        self.horizontalLayout_2.addWidget(self.labelStartDate)
        self.comboBox = QtWidgets.QComboBox(parent=ShowReports)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(parent=ShowReports)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(parent=ShowReports)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableVendors = QtWidgets.QTableWidget(parent=ShowReports)
        self.tableVendors.setRowCount(0)
        self.tableVendors.setColumnCount(0)
        self.tableVendors.setObjectName("tableVendors")
        self.verticalLayout.addWidget(self.tableVendors)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonAdd = QtWidgets.QPushButton(parent=ShowReports)
        self.buttonAdd.setEnabled(False)
        self.buttonAdd.setAutoDefault(False)
        self.buttonAdd.setDefault(True)
        self.buttonAdd.setObjectName("buttonAdd")
        self.horizontalLayout.addWidget(self.buttonAdd)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ShowReports)
        QtCore.QMetaObject.connectSlotsByName(ShowReports)

    def retranslateUi(self, ShowReports):
        _translate = QtCore.QCoreApplication.translate
        ShowReports.setWindowTitle(_translate("ShowReports", "Mostra informes"))
        self.labelEndDate.setText(_translate("ShowReports", "<html><head/><body><h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:700;\">Informes</span></h1></body></html>"))
        self.labelStartDate.setText(_translate("ShowReports", "Tipus d\'informe"))
        self.label_2.setText(_translate("ShowReports", "Any:"))
        self.buttonAdd.setText(_translate("ShowReports", "Exporta a CSV"))
