# Form implementation generated from reading ui file 'src\ui\show_error.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 158)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelErrorIcon = QtWidgets.QLabel(parent=Dialog)
        self.labelErrorIcon.setEnabled(True)
        self.labelErrorIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.labelErrorIcon.setText("")
        self.labelErrorIcon.setPixmap(QtGui.QPixmap(":/resources/icons/error.png"))
        self.labelErrorIcon.setScaledContents(True)
        self.labelErrorIcon.setObjectName("labelErrorIcon")
        self.horizontalLayout.addWidget(self.labelErrorIcon)
        self.labelErrorDescription = QtWidgets.QLabel(parent=Dialog)
        self.labelErrorDescription.setObjectName("labelErrorDescription")
        self.horizontalLayout.addWidget(self.labelErrorDescription)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.btnClose = QtWidgets.QPushButton(parent=Dialog)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout_2.addWidget(self.btnClose)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelErrorDescription.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">ErrorDescription</span></p></body></html>"))
        self.btnClose.setText(_translate("Dialog", "Tanca"))
